remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DSpec Framework
description: A framework for Declarative, Specification-Driven Software Development. Aimed at Agentic workflows, influenced by Domain Driven Design.